### ISSUE TITLE
Problem in python3 train.py ocr

### ISSUE THREAD

**Issue by Rwik2000** [breadbread1984/OCR-tf2#2]
I am getting the following error. Ran one of your previous versions.

`Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7f646975cb70> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x7f6469754550>).
Traceback (most recent call last):
  File "train.py", line 122, in <module>
    train_ocr();
  File "train.py", line 75, in train_ocr
    checkpoint.restore(tf.train.latest_checkpoint('checkpoints'));
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 2009, in restore
    status = self._saver.restore(save_path=save_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 1304, in restore
    checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 209, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 907, in _restore_from_checkpoint_position
    tensor_saveables, python_saveables))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 289, in restore_saveables
    validated_saveables).restore(self.save_path_tensor)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saving/functional_saver.py", line 281, in restore
    restore_ops.update(saver.restore(file_prefix))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saving/functional_saver.py", line 103, in restore
    restored_tensors, restored_shapes=None)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saving/saveable_object_util.py", line 116, in restore
    self.handle_op, self._var_shape, restored_tensor)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 308, in shape_safe_assign_variable_handle
    shape.assert_is_compatible_with(value_tensor.shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py", line 1117, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (32,) and (64,) are incompatible`

Was there any problem with the previous code? Should I try the updated code?

**Comment by breadbread1984** [comment]
delete checkpoint directory before training with different code.
